<a href="https://colab.research.google.com/github/Indongspace/mulcamp34/blob/main/Ch2_240119.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
!pip install pandas

In [ ]:
import numpy as np
import pandas as pd

# jupyter notebook 의 출력을 소수점 이하 3자리로 제한
%precision 3
# dataframe의 출력을 소수점 이하 3자리로 제한
#pd.set_option('precision',3)

'%.3f'

In [ ]:
df = pd.read_csv('venv/source/python_stat_sample-master/data/ch2_scores_em.csv',index_col='student number')
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [ ]:
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [ ]:
scores_df = pd.DataFrame({'score':scores},
                        index=pd.Index(['A','B','C','D','E','F','G','H','I','J'],name='student'))

scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

In [ ]:
sum(scores)/len(scores)

55.000

In [ ]:
np.mean(scores)

55.000

In [ ]:
scores_df.mean()

score    55.0
dtype: float64

In [ ]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [ ]:
n = len(sorted_scores)
if n%2==0:
    m0 = sorted_scores[n//2-1]
    m1 = sorted_scores[n//2]
    median = (m0+m1)/2
else:
    median = sorted_scores[(n+1)//2-1]

median

56.500

In [ ]:
np.median(scores)

56.500

In [ ]:
scores_df.median()

score    56.5
dtype: float64

In [ ]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [ ]:
pd.Series([1,2,3,4,5]).mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [ ]:
another_scores = [50,60,58,54,51,56,57,53,52,59]
another_mean = np.mean(another_scores)
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [ ]:
np.mean(deviation)

0.000

In [ ]:
np.mean(another_deviation)

0.000

In [ ]:
summary_df = scores_df.copy()
summary_df['deviation'] = deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [ ]:
summary_df.mean()

score        55.0
deviation     0.0
dtype: float64

In [ ]:
np.mean(deviation**2)

86.000

In [ ]:
np.var(scores)

86.000

In [ ]:
scores_df.var()

score    95.555556
dtype: float64

In [ ]:
scores_df.var(ddof=0)

score    86.0
dtype: float64

In [ ]:
summary_df['square of deviation'] = np.square(deviation)
summary_df

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

In [ ]:
summary_df.mean()

score                  55.0
deviation               0.0
square of deviation    86.0
dtype: float64

In [ ]:
np.sqrt(np.var(scores,ddof=0))

9.274

In [ ]:
np.std(scores,ddof=0)

9.274

In [ ]:
np.max(scores) - np.min(scores)

28

In [ ]:
scores_Q1 = np.percentile(scores,25) # 48.250
scores_Q3 = np.percentile(scores,75) # 63.250
scores_IQR = scores_Q3 - scores_Q1
scores_IQR
# scores_Q2 = np.percentile(scores,50) # 56.500

15.000

In [ ]:
pd.Series(scores).describe()

count    10.000000
mean     55.000000
std       9.775252
min      41.000000
25%      48.250000
50%      56.500000
75%      63.250000
max      69.000000
dtype: float64

In [ ]:
z = (scores - np.mean(scores))/np.std(scores)
z

array([-1.402,  1.51 ,  0.108, -1.51 ,  0.216, -0.755,  1.078, -0.647,
        1.078,  0.323])

In [ ]:
np.mean(z),np.std(z,ddof=0)

(-0.000, 1.000)

In [ ]:
z = 50 + ((10*(scores - np.mean(scores)))/np.std(scores))
z

array([35.982, 65.097, 51.078, 34.903, 52.157, 42.452, 60.783, 43.53 ,
       60.783, 53.235])

In [ ]:
scores_df['deviation value'] = z
scores_df

score  deviation value
student                        
A           42        35.981739
B           69        65.096588
C           56        51.078328
D           41        34.903412
E           57        52.156655
F           48        42.451706
G           65        60.783277
H           49        43.530034
I           65        60.783277
J           58        53.234983